### ISSUE TITLE
Crash on railing offset adjustment

### ISSUE THREAD

**Issue by DDoop** [ranjian0/building_tool#96] opened 2020-05-25 17:47 UTC
Crash to desktop when entering invalid value for "Railing offset" on balcony.
Steps to recreate:
1) Create simple floorplan (this bug also happens with more complicated plans as well, but it is not necessary).
2) Add a floor.
3) Pick one of the sides of the building, then add a balcony.
4) Increase the value of the "railing offset" slider. It should crash just above .47 with the default balcony settings.
I tested this on 2.90 pre-release and a fresh install of the latest stable release with factory settings (2.82a). Both crashed. The 2.82a version actually took a greater value than .47 in the offset field, but still crashed about a second after passing 0.47.
0.47 is when the railing starts to invert across itself, by the way.
I've attached the crash log for one of the 2.90 crashes, since I can't find where Blender is storing the ones from 2.82a.
[blender.crash.txt](https://github.com/ranjian0/building_tool/files/4678356/blender.crash.txt)

**Comment by ranjian0** [comment] 2020-05-25 17:55
Yep! Just reproduced!!
```
Error: Traceback (most recent call last):
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/balcony/balcony_ops.py", line 22, in execute
    return Balcony.build(context, self.props)
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/balcony/balcony.py", line 17, in build
    create_balcony(bm, faces, prop)
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/balcony/balcony_types.py", line 37, in create_balcony
    add_railing_to_balcony(bm, top, normal, prop)
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/balcony/balcony_types.py", line 72, in add_railing_to_balcony
    create_railing(bm, railing_faces, prop.rail, balcony_normal)
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/railing/railing.py", line 24, in create_railing
    make_fill(bm, f, prop)
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/railing/railing.py", line 42, in make_fill
    top_edge = sort_edges(non_vertical, Vector((0., 0., -1.)))[0]
IndexError: list index out of range

location: <unknown location>:-1
```
That's my traceback.

**Comment by IshoAntar** [comment] 2020-05-27 06:16
The issue is cause by indexing an empty list returned from `sort_edges`. i managed to resolve it by checking if the list is empty before indexing, and returning early if it is. however this causes another bug (screenshot below).

To be honest i don't have much experience with python, how the add-on works nor blender's API so i don't know how to fix this, but i don't think that anyone would will "merge" a railing like this so i think it's safe for now!

Also, there are a lot of instances in the source code where this occurs (indexing a list without checking if it contains anything) that should be fixed.

![Screenshot_20200527_090850](https://user-images.githubusercontent.com/32076082/82984205-51b9e880-9ffa-11ea-9d16-0af23d1a9456.png)

**Comment by ranjian0** [comment] 2020-05-27 13:53
> Also, there are a lot of instances in the source code where this occurs (indexing a list without checking if it contains anything) that should be fixed.

This is true, just had a look in one of the modules. Loads of indexing without checks. I'd prefer to have a new issue tackling this.

**Closed** 2020-06-07 14:08 UTC
Labels: bug
