### ISSUE TITLE
Custom Objects

### ISSUE THREAD

**Issue by SamTangent** [ranjian0/building_tool#98] opened 2020-05-25 18:47 UTC
Possibility to add custom windows, objects and doors etc. Doesn't need to have all the customization of the current system but a quick way for someone to build a door they would like, select as an object and add it into the system for them to use. In the future it could be a mini-asset system but I think a quick way to just add custom objects would be ideal for this.

**Comment by ranjian0** [comment] 2020-05-25 21:13
Might this be similar to #95.

**Comment by ranjian0** [comment] 2020-05-27 19:20
Closing as duplicate of #95.

**Closed by ranjian0** 2020-05-27 19:20 UTC
