### ISSUE TITLE
.97 Stable version error

### ISSUE THREAD

**Issue by tarnis** [ranjian0/building_tool#46] opened 2020-04-06 20:45 UTC
Getting this error in both the stable and dev versions...Master just crashes blender when I get to the roof portion.

![image](https://user-images.githubusercontent.com/22822314/78603336-9193f900-781d-11ea-9814-2aa958195097.png)

**Comment by ranjian0** [comment] 2020-04-07 08:43
- `dev` version is not stable. Avoid at all costs.
- Just pushed a fix for the above error in `stable`.

**Comment by ranjian0** [comment] 2020-04-07 08:56
Roof in `master` and `stable` should now be ok after 57a389d4c894893b18686451b4e0cc00e24e54cb and de279a950d21e3ec1e23a53cd884dca0dca6e647

**Comment by ranjian0** [comment] 2020-04-07 08:57
Please close the issue if satisfied with the fixes.
Open a new issue for other problems.
Cheers.

**Comment by tarnis** [comment] 2020-04-07 16:03
Still having issues, roof isn't crashing it but the slab is now.  Blender just blips out, no error.

**Comment by ranjian0** [comment] 2020-04-07 18:40
> Still having issues, roof isn't crashing it but the slab is now. Blender just blips out, no error. Thankyou for correcting the other part so promptly.

Do you mean slab from the floors tool. Which tool exactly and what properties did you change to cause the crash

**Comment by tarnis** [comment] 2020-04-09 16:23
Yes...  Doesn't seem to matter.  The standard four sided as well as the composite if I reduce the size of the slab it crashes.

**Comment by ranjian0** [comment] 2020-04-09 16:32
> Yes... Doesn't seem to matter. The standard four sided as well as the composite if I reduce the size of the slab it crashes.

Unable to reproduce this in any of the branches. Tested current `master`, `stable` and `dev`

**Comment by tarnis** [comment] 2020-04-09 17:26
.9.7 Stable the version I should be on?

**Comment by tarnis** [comment] 2020-04-09 17:30
Should I still be downloading .97?  The other stuff seems fixed but having this problem.  Dunno.

**Comment by tarnis** [comment] 2020-04-09 17:36
https://photos.app.goo.gl/L2Mxf6b7phSNbXm29

**Comment by tarnis** [comment] 2020-04-09 18:08
https://photos.app.goo.gl/5tjdqQbB2Gnqrbxj9

**Comment by ranjian0** [comment] 2020-04-09 19:46
> Should I still be downloading .97? The other stuff seems fixed but having this problem. Dunno.

Lots of changes are happening and currently release 0.97 is over 60 commits behind `master`. 
If you feel adventurous, try out `master`. It should be working nicely but still beware. Issues #43 and #45 have still not been fixed. Plus others that have not been discovered.

The next release will be version 1.0 in May. That's when you can expect an official release without this bug.

**Comment by tarnis** [comment] 2020-04-09 20:39
Thanks, Will try.

**Comment by ranjian0** [comment] 2020-04-09 20:42
Please close the issue if satisfied.

**Closed** 2020-04-09 20:57 UTC
